site: taloranderson.com
url: https://taloranderson.com
title: Talor Anderson
description: Hi! I'm Talor Anderson.

resume_url: 'https://drive.google.com/open?id=18YST_yucGyDjMK506xMjzbOLX2i116HI'
twitter_username: talor_a

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  notes:
    output: true
    permalink: /:year-:month-:day:output_ext
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      defaults:
  - 
    scope:
      path: "wiki/*"
    values:
      layout: "wiki"