site: taloranderson.com
url: #yoururl
title: Talor Anderson
description: Hi! I'm Talor Anderson.

resume_url: 'https://drive.google.com/open?id=18YST_yucGyDjMK506xMjzbOLX2i116HI'
twitter:
  username: #yourusername
  card: summary
  creator: #yourusername
author:
  twitter: #yourusername
  name: #yourusername
  avatar:
  email: #youremail
  url: #yoururl

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  journal:
    output: true
    permalink: /:year-:month-:day:output_ext
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      defaults:
  - 
    scope:
      path: "notes/*"
    values:
      layout: "wiki"